### ISSUE TITLE
deleted files causing issues

### ISSUE THREAD

**Issue by laggingreflex** [appnexus/sicksync#76]
```
fs.js:557
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\...\projects\...\npm-debug.log.334085093'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at FSHelper.onFileChange (C:\...\sicksync\dist\local\fs-helper.js:83:72)
    at Timeout._onTimeout (C:\...\sicksync\dist\util.js:145:17)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by laggingreflex** [comment]
fixed by #83
